init:
  - git config --global core.autocrlf input
  - git config --global core.eol lf

branches:
  only:
    - master
    - develop

skip_branch_with_pr: true

environment:
  matrix:
    - node: "4"
    - node: "5"
    - node: "6"
    - node: "7"

services:
  - mongodb

matrix:
  allow_failures:
    - node: "5"

cache:
  - node_modules -> package.json

install:
  - ps: Install-Product node $env:node
  - appveyor-retry npm install

build: off # Disable MSBuilds, not related to the regular build process

test_script:
  - node --version && npm --version
  - cmd: "npm test"

deploy: off
